=== iqb-specifications/metadata-profile/metadata-profile.schema.json
{
  "$id": "metadata-profile@iqb-standard@0.10",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metadata Profile",
  "description": "Data interface for defining metadata for objects based on vocabularies of IQB.",
  "type": "object",

  "properties": {
    "id": {
      "type": "string",
      "description": "Identifier for the metadata profile"
    },
    "label": {
      "$ref": "#/definitions/language_coded_texts",
      "description": "Name of the profile"
    },
    "profileType": {
      "type": "string",
      "enum": [
        "unit",
        "item",
        "research_study",
        "copyright"
      ],
      "description": "Type of profile"
    },
    "groups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "$ref": "#/definitions/language_coded_texts"
          },
          "entries": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/entry"
            },
            "minItems": 1
          }
        },
        "required": ["label", "entries"]
      },
      "minItems": 1
    }
  },
  "required": ["id", "label", "profileType", "groups"],
  "definitions": {
    "language_coded_texts": {
      "type": "array",
      "description": "Used for storing the input of texts. This type applies also in cases when only one language is used.",
      "items": {
        "type": "object",
        "properties": {
          "lang": {
            "type": "string",
            "minLength": 1,
            "description": "ISO-language code",
            "pattern": "^[a-z]{2}$"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "lang",
          "value"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "vocabulary": {
      "type": "object",
      "description": "Creates values of type string (one possible id), string[] (multiple ids) or id+text tuples, if text input is allowed.",
      "properties": {
        "url": {
          "type": "string",
          "description": "URI to the JSON representation (SkoHub) of the vocabulary definition"
        },
        "allowMultipleValues": {
          "type": "boolean",
          "description": "If true, multiple values are allowed taken from the vocabulary",
          "default": false
        },
        "selectionMode": {
          "type": "string",
          "enum": ["in-form", "dialog"],
          "description": "UI variants: 'in-form' sets an radio or checkbox list in the form, 'dialog' challenges a modal dialog for selection (default).",
          "default": "dialog"
        },
        "maxLevel": {
          "type": "integer",
          "description": "Maximum level taken from the hierarchical vocabulary. This is to hide lower levels. Use '0' for all levels (default).",
          "default": 0
        },
        "hideNumbering": {
          "type": "boolean",
          "description": "If true, the numbering of vocabulary entries is not used/showed in components.",
          "default": false
        },
        "hideDescription": {
          "type": "boolean",
          "description": "If true, the description of vocabulary entries is not used/showed in components.",
          "default": false
        },
        "hideTitle": {
          "type": "boolean",
          "description": "If true, the title of vocabulary entries is not used/showed in components.",
          "default": false
        },
        "addTextLanguages": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "ISO-language code",
            "pattern": "^[a-z]{2}$"
          },
          "description": "If not empty, text can be added to the selected vocabulary entry. The given entries specify the expected language(s).",
          "default": []
        }
      },
      "required": ["url"]
    },
    "text": {
      "type": "object",
      "description": "Creates values of type string (one possible language) or multi-language texts.",
      "properties": {
        "format": {
          "type": "string",
          "enum": ["single", "multiline", "html"],
          "description": "If true, more then one line of text is prepared for input. Text is wrapped and vertical scrolling is possible.",
          "default": "single"
        },
        "textLanguages": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "ISO-language code",
            "pattern": "^[a-z]{2}$"
          },
          "description": "Use this property to add languages, so you provide more then one text input form field.",
          "default": [
            "de"
          ]
        },
        "pattern": {
          "type": "string",
          "description": "Use this regular expression to validate the input value."
        }
      }
    },
    "number": {
      "type": "object",
      "description": "Creates values of type string with number content. The decimal separator is always dot '.'.",
      "properties": {
        "digits": {
          "type": "integer",
          "description": "Number of digits. Negative values are not valid.",
          "minimum": 0,
          "default": 0
        },
        "minValue": {
          "type": "number",
          "description": "Minimal value valid for this entry."
        },
        "maxValue": {
          "type": "number",
          "description": "Maximal value valid for this entry."
        },
        "isPeriodSeconds": {
          "type": "boolean",
          "description": "If true, the (integer) value is interpreted as a number of seconds (duration, time period). This might adapt the form controls.",
          "default": false
        }
      }
    },
    "boolean": {
      "type": "object",
      "description": "Creates values of type string 'true' or 'false'.",
      "properties": {
        "trueLabel": {
          "$ref": "#/definitions/language_coded_texts"
        },
        "falseLabel": {
          "$ref": "#/definitions/language_coded_texts"
        }
      }
    },
    "entry": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^[a-zA-Z][0-9a-zA-Z_]*$",
          "description": "Identifier for the property as part of the metadata profile"
        },
        "label": {
          "$ref": "#/definitions/language_coded_texts",
          "description": "Text presented in UI components as prompt"
        },
        "type": {
          "type": "string",
          "enum": ["text", "vocabulary", "boolean", "number"]
        },
        "parameters": {
          "anyOf": [
            {
              "$ref": "#/definitions/vocabulary"
            },
            {
              "$ref": "#/definitions/text"
            },
            {
              "$ref": "#/definitions/number"
            },
            {
              "$ref": "#/definitions/boolean"
            }
          ]
        }
      },
      "required": ["id", "type"]
    }
  }
}

=== iqb-specifications/metadata-profile/test/test_valid/research_type.json
{
  "id": "https://raw.githubusercontent.com/iqb-vocabs/p52/master/unit.json",
  "label": [{
    "lang": "de",
    "value": "IQB Französisch Sek I - Aufgabe"
  }],
  "profileType": "research_study",
  "groups": [
    {
      "label": [
        {
          "lang": "de",
          "value": "Stimulus"
        }
      ],
      "entries": [
        {
          "id": "e2",
          "label": [
            {
              "lang": "de",
              "value": "Textniveau (GeR)"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v26/ng/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "e3",
          "label": [
            {
              "lang": "de",
              "value": "Textkomplexität: Lexiko-Grammatik"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/le/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "e4",
          "label": [
            {
              "lang": "de",
              "value": "Textkomplexität: Abstraktionsgrad"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/ta/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "e5",
          "label": [
            {
              "lang": "de",
              "value": "Textkomplexität: Thematischer Vertrautheitsgrad"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/ve/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "e6",
          "label": [
            {
              "lang": "de",
              "value": "Textsorte"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/te/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "iqb_other_text_type",
          "label": [
            {
              "lang": "de",
              "value": "Andere Textsorte"
            }
          ],
          "type": "text",
          "parameters": {
            "format": "single"
          }
        },
        {
          "id": "e7",
          "label": [
            {
              "lang": "de",
              "value": "Thema"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/th/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "iqb_other_topic",
          "label": [
            {
              "lang": "de",
              "value": "Anderes Thema"
            }
          ],
          "type": "text",
          "parameters": {
            "format": "single"
          }
        },
        {
          "id": "iqb_time_stimulus",
          "label": [
            {
              "lang": "de",
              "value": "Länge des verwendeten Audioauszugs"
            }
          ],
          "type": "number",
          "parameters": {
            "minValue": 0,
            "digits": 0,
            "isPeriodSeconds": true
          }
        },
        {
          "id": "iqb_word_count",
          "label": [
            {
              "lang": "de",
              "value": "Wortanzahl"
            }
          ],
          "type": "number",
          "parameters": {
            "minValue": 0,
            "digits": 0
          }
        },
        {
          "id": "iqb_time_unit",
          "label": [
            {
              "lang": "de",
              "value": "Aufgabenzeit"
            }
          ],
          "type": "number",
          "parameters": {
            "minValue": 0,
            "digits": 0,
            "isPeriodSeconds": true
          }
        },
        {
          "id": "iqb_compatibility",
          "label": [
            {
              "lang": "de",
              "value": "Unverträgliche Aufgaben"
            }
          ],
          "type": "text",
          "parameters": {
            "format": "single"
          }
        },
        {
          "id": "iqb_phones",
          "label": [
            {
              "lang": "de",
              "value": "Kopfhörereinsatz"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v24/kh/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "kim_type_school",
          "label": [
            {
              "lang": "de",
              "value": "Schulform"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/kim/schularten/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        }
      ]
    },
    {
      "label": [
        {
          "lang": "de",
          "value": "Quellenangaben"
        }
      ],
      "entries": [
        {
          "id": "iqb_copyright_citation",
          "label": [
            {
              "lang": "de",
              "value": "Vermerk / Zitation"
            }
          ],
          "type": "text",
          "parameters": {
            "format": "multiline"
          }
        },
        {
          "id": "iqb_copyright_original",
          "label": [
            {
              "lang": "de",
              "value": "Transkript Original / Text Original"
            }
          ],
          "type": "text",
          "parameters": {
            "format": "multiline"
          }
        }
      ]
    },
    {
      "label": [
        {
          "lang": "de",
          "value": "Hörsequenz"
        }
      ],
      "entries": [
        {
          "id": "k2",
          "label": [
            {
              "lang": "de",
              "value": "Sprecheranzahl / Sprechermerkmale"
            }
          ],
          "type": "text",
          "parameters": {
            "format":  "single"
          }
        },
        {
          "id": "k3",
          "label": [
            {
              "lang": "de",
              "value": "Sprechtempo"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/sp/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "k4",
          "label": [
            {
              "lang": "de",
              "value": "Varianten"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/fv/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "k5",
          "label": [
            {
              "lang": "de",
              "value": "Nebengeräusche"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v25/ne/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "iqb_final_transcript",
          "label": [
            {
              "lang": "de",
              "value": "Transkript zur Aufgabe"
            }
          ],
          "type": "text",
          "parameters": {
            "format": "multiline"
          }
        }
      ]
    }
  ]
}

=== iqb-specifications/metadata-profile/test/test_valid/item1.json
{
  "id": "https://raw.githubusercontent.com/iqb-vocabs/p14/master/item.json",
  "label": [{
    "lang": "de",
    "value": "IQB Deutsch Primar 2004 - Item"
  }],
  "profileType": "item",
  "groups": [
    {
      "label": [
        {
          "lang": "de",
          "value": "Item"
        }
      ],
      "entries": [
        {
          "id": "s3",
          "label": [
            {
              "lang": "de",
              "value": "Itemformat"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v27/dp/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "s4",
          "label": [
            {
              "lang": "de",
              "value": "Anforderungsbereich"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v13/a1/",
            "allowMultipleValues": false,
            "hideNumbering": true
          }
        },
        {
          "id": "s5",
          "label": [
            {
              "lang": "de",
              "value": "Bildungsstandard primär"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v13/k1/",
            "allowMultipleValues": false
          }
        },
        {
          "id": "s6",
          "label": [
            {
              "lang": "de",
              "value": "Bildungsstandards sekundär"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v13/k1/",
            "allowMultipleValues": true
          }
        },
        {
          "id": "iqb_time_item",
          "label": [
            {
              "lang": "de",
              "value": "Itemzeit"
            }
          ],
          "type": "number",
          "parameters": {
            "minValue": 0,
            "digits": 0,
            "isPeriodSeconds": true
          }
        },
        {
          "id": "e4",
          "label": [
            {
              "lang": "de",
              "value": "Geschätzte Schwierigkeit"
            }
          ],
          "type": "vocabulary",
          "parameters": {
            "url": "https://w3id.org/iqb/v26/ea/",
            "allowMultipleValues": false
          }
        }
      ]
    }
  ]
}
